force-app/main/default/objects/ExpenseCard__c/ExpenseCard__c.object-meta.xml
<CustomObject>
    <label>ExpenseCard</label>
    <nameField>
        <label>ExpenseCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpenseCards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpenseCard__c/fields/CardDate__c.field-meta.xml
<CustomField>
    <fullName>CardDate__c</fullName>
    <label>CardDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpenseCard__c/fields/CardKeeper__c.field-meta.xml
<CustomField>
    <fullName>CardKeeper__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CardKeeper</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ExpenseCards</relationshipLabel>
    <relationshipName>Expence_Cards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpenseCard__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExpenseCard__c/fields/MonthlyExpense__c.field-meta.xml
<CustomField>
    <fullName>MonthlyExpense__c</fullName>
    <label>MonthlyExpense</label>
    <referenceTo>MonthlyExpense__c</referenceTo>
    <relationshipLabel>ExpenseCards</relationshipLabel>
    <relationshipName>Expence_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MonthlyExpense__c/MonthlyExpense__c.object-meta.xml
<CustomObject>
    <label>MonthlyExpense</label>
    <nameField>
        <label>MonthlyExpense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MonthlyExpenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonthlyExpense__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccordController.cls
public with sharing class AccordController {
   
@AuraEnabled(cacheable=true)
public static List<ExpenseCard__c> getExpenseCards(Date cardDate,String login,String password){
    try {
       
        return [Select Description__c,Amount__c,CardDate__c from ExpenseCard__c
        where CardDate__c =: cardDate AND CardKeeper__r.Password__c =: password 
        AND CardKeeper__r.Email =: login ];
        
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
  }
 
  @AuraEnabled(cacheable = true)
  public static List<Decimal> getSum(Date cardDate,String login,String password){
      try {
        Decimal total = 0;
        List <ExpenseCard__c> exList =  getExpenseCards(cardDate, login,password);
        List<Decimal>sumList = new List<Decimal>();
        for(Expensecard__c exCard : exList){
        total = total + exCard.Amount__c;
        }
        sumList.add(total);
        return sumList;
      } catch (Exception e) {
          throw new AuraHandledException(e.getMessage());
      }
  }
  @AuraEnabled
  public static void deleteCard(Id cardId){
      try {
         List<ExpenseCard__c>exList = [select Id,Amount__c,MonthlyExpense__c from ExpenseCard__c where Id =: cardId LIMIT 1];
         List <MonthlyExpense__c> monExList = [select Balance__c from MonthlyExpense__c where Id = :exList[0].MonthlyExpense__c LIMIT 1];     
         monExList[0].Balance__c += exList[0].Amount__c;
         upsert monExList;
          
         delete exList[0];
      } catch (Exception e) {
          throw new AuraHandledException(e.getMessage());
      }
  }
  
}