force-app/main/default/objects/ExpenseCard__c/ExpenseCard__c.object-meta.xml
<CustomObject>
    <label>ExpenseCard</label>
    <nameField>
        <label>ExpenseCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpenseCards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpenseCard__c/fields/CardDate__c.field-meta.xml
<CustomField>
    <fullName>CardDate__c</fullName>
    <label>CardDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpenseCard__c/fields/CardKeeper__c.field-meta.xml
<CustomField>
    <fullName>CardKeeper__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CardKeeper</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ExpenseCards</relationshipLabel>
    <relationshipName>Expence_Cards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpenseCard__c/fields/MonthlyExpense__c.field-meta.xml
<CustomField>
    <fullName>MonthlyExpense__c</fullName>
    <label>MonthlyExpense</label>
    <referenceTo>MonthlyExpense__c</referenceTo>
    <relationshipLabel>ExpenseCards</relationshipLabel>
    <relationshipName>Expence_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MonthlyExpense__c/MonthlyExpense__c.object-meta.xml
<CustomObject>
    <label>MonthlyExpense</label>
    <nameField>
        <label>MonthlyExpense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MonthlyExpenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonthlyExpense__c/fields/Keeper__c.field-meta.xml
<CustomField>
    <fullName>Keeper__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Keeper</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MonthlyExpenses</relationshipLabel>
    <relationshipName>MonthlyExpenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MonthlyExpense__c/fields/MonthDate__c.field-meta.xml
<CustomField>
    <fullName>MonthDate__c</fullName>
    <label>MonthDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    public static Contact createEmployeeWithExCard(Date cardDate,String email,String password,String office){
        Contact con = New Contact(FirstName = 'Andrei',LastName = 'jjj',Email = email,Password__c = password,Office__c = office);
        insert con;
        ExpenseCard__c exC = new ExpenseCard__c(CardDate__c = cardDate,CardKeeper__c = con.Id,Amount__c = 100);
        insert exC;
       return con;
    }
       
    public static ExpenseCard__c createExpenseCard(Date cardDate,String email,String password,String office){
        Contact con = new Contact(FirstName = 'Andrei',LastName = 'jjj',Email = email,Password__c = password,Office__c = office);
        insert con;
        ExpenseCard__c exC = new ExpenseCard__c(CardDate__c = cardDate,CardKeeper__c = con.Id,Amount__c = 100);
        
        insert exC;
        return exC;
    }
    public static MonthlyExpense__c createMonthlyExpenseWithCard(){
         Contact con = new Contact(FirstName = 'Andre',LastName = 'jj',Email = 'ggggg@mail.ru',Password__c = 'ff');
         insert con;
         MonthlyExpense__c mE = new MonthlyExpense__c(MonthDate__c = Date.newInstance(2023, 1, 1),Keeper__c = con.Id);
         ExpenseCard__c exC = new ExpenseCard__c(CardDate__c = Date.newInstance(2023, 1, 1),CardKeeper__c = con.Id);
      insert mE;
      insert exC;
      return mE;
     }
}