force-app/main/default/objects/ExpenseCard__c/ExpenseCard__c.object-meta.xml
<CustomObject>
    <label>ExpenseCard</label>
    <nameField>
        <label>ExpenseCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpenseCards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpenseCard__c/fields/MonthlyExpense__c.field-meta.xml
<CustomField>
    <fullName>MonthlyExpense__c</fullName>
    <label>MonthlyExpense</label>
    <referenceTo>MonthlyExpense__c</referenceTo>
    <relationshipLabel>ExpenseCards</relationshipLabel>
    <relationshipName>Expence_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MonthlyExpense__c/MonthlyExpense__c.object-meta.xml
<CustomObject>
    <label>MonthlyExpense</label>
    <nameField>
        <label>MonthlyExpense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MonthlyExpenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EmployeeControllerTest.cls
@isTest
public class EmployeeControllerTest {
 
  @isTest static void emTest(){
      MonthlyExpense__c mE = EmployeeController.getMonEx(2023,1,'gggg','gggg');
      List<Decimal> mESE = EmployeeController.getMonExSpentAm(2023,1,'gggg','gggg');
      List<Decimal>mEI = EmployeeController.getMonExIncome(2023,1,'gggg','gggg');
      List<MonthlyExpense__c>mEE = EmployeeController.getMonthlyExpense(2023,'gggg','gggg');
      List<Integer> yFT = EmployeeController.getYearForTab();
      List<Date> dateL = EmployeeController.populateDates(2023,1);
      List<Decimal> amTot = EmployeeController.getAmountTotal(2023,'gggg','gggg');   
      List<Decimal> yearInc = EmployeeController.getYearIncome(2023,'gggg','gggg');
      List<ExpenseCard__c> eCards = EmployeeController.getExCards(1,2023,'gggg','gggg');
      Contact con = TestDataFactory.createEmployeeWithExCard(Date.newInstance(2023, 1, 1),'hhhh@dot.com','gggg','Office 1');
      EmployeeController.saveExpenseCard(123,Date.newInstance(2023, 1, 1),'Yahoo',
      con.Id);
      EmployeeController.saveIncomeInput(122,Date.newInstance(2023, 1, 1),con.Id);
      List<string>monthNames = EmployeeController.getMonthNameFromNum(3);
      
      
  }
}