force-app/main/default/objects/ExpenseCard__c/ExpenseCard__c.object-meta.xml
<CustomObject>
    <label>ExpenseCard</label>
    <nameField>
        <label>ExpenseCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpenseCards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpenseCard__c/fields/MonthlyExpense__c.field-meta.xml
<CustomField>
    <fullName>MonthlyExpense__c</fullName>
    <label>MonthlyExpense</label>
    <referenceTo>MonthlyExpense__c</referenceTo>
    <relationshipLabel>ExpenseCards</relationshipLabel>
    <relationshipName>Expence_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MonthlyExpense__c/MonthlyExpense__c.object-meta.xml
<CustomObject>
    <label>MonthlyExpense</label>
    <nameField>
        <label>MonthlyExpense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MonthlyExpenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AdminControllerTest.cls
@isTest
public class AdminControllerTest {
  @isTest static void AdmnTest(){
      ExpenseCard__c eCc = TestDataFactory.createExpenseCard(Date.newInstance(2022, 1, 1),'gggg@mail.ru','lllf','Office 1');
      ExpenseCard__c eC = TestDataFactory.createExpenseCard(Date.newInstance(2023, 1, 1),'ggg@mail.ru','ff','Office 2');
      MonthlyExpense__c mE = TestDataFactory.createMonthlyExpenseWithCard();
      List <MonthlyExpense__c> monExList = AdminController.getOfficeMonthlyExpenses(2023,'Office 1');
      List <Decimal> ofMonSpAm = AdminController.getOfficeMonthlySpentAmount(2023,1,'Office 1');
      List<Decimal> sList = AdminController.getSumList(2023);
      Decimal ofBal = AdminController.getOfficeBalanceNow('Office 5');
      List<Decimal> monAv = AdminController.getMonthlyAverage(2023,'Office 1');
      List<Decimal> yearSum = AdminController.getYearSum(2023);
      List<Decimal>ofYES = AdminController.getOfficeYearExpenseSum(2023,'Office 1');
      List<Contact>conL = AdminController.getOfficeEmployees('Office 1');
      Contact con = TestDataFactory.createEmployeeWithExCard(Date.newInstance(2023, 1, 1),'jjjjj@uut.by','oooops','Office 1');
      List<Decimal>ofEME = AdminController.getOfEmpMonEx(con.Id,2023,1);
      List<Decimal>empYE = AdminController.getEmployeeYearExpense(con.Id,2023);
      
  }
}