force-app/main/default/objects/ExpenseCard__c/ExpenseCard__c.object-meta.xml
<CustomObject>
    <label>ExpenseCard</label>
    <nameField>
        <label>ExpenseCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpenseCards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpenseCard__c/fields/MonthlyExpense__c.field-meta.xml
<CustomField>
    <fullName>MonthlyExpense__c</fullName>
    <label>MonthlyExpense</label>
    <referenceTo>MonthlyExpense__c</referenceTo>
    <relationshipLabel>ExpenseCards</relationshipLabel>
    <relationshipName>Expence_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MonthlyExpense__c/MonthlyExpense__c.object-meta.xml
<CustomObject>
    <label>MonthlyExpense</label>
    <nameField>
        <label>MonthlyExpense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MonthlyExpenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccordControllerTest.cls
@isTest
public class AccordControllerTest {
    @isTest static void getExpenseCardsTest(){
    
    ExpenseCard__c exC = TestDataFactory.createExpenseCard(Date.newInstance(2023, 1, 1),'gggggg@mail.ru','fff','Office 1');
    
    List<Decimal> sum = AccordController.getSum(Date.newInstance(2023, 1, 1),'gggggg@mail.ru','fff');
   
    List<ExpenseCard__c> exCardsList = AccordController.getExpenseCards(Date.newInstance(2023, 1, 1),'gggggg@mail.ru','fff');
    AccordController.deleteCard(exCardsList[0].Id);
    
    }
    @isTest static void getExpenseCardsWithMETest(){
    MonthlyExpense__c mE = TestDataFactory.createMonthlyExpenseWithCard();
    ExpenseCard__c exC = TestDataFactory.createExpenseCard(Date.newInstance(2023, 1, 1),'gggggg@mail.ru','fff','Office 1');
    
    }
}